services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx:inception
    env_file:
      - ./.env
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html:ro
    networks:
      - inception_network
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:inception
    container_name: mariadb
    env_file:
      - ./.env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network
    secrets:
      - db_password
      - db_root_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped
# ========================== VOLUMES ===============================
volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/lsilva-x/data/wordpress"
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/lsilva-x/data/mariadb"
# ========================== SECRETS ===============================
secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
# ========================== NETWORK ===============================
networks:
  inception_network:
    driver: bridge
    name: inception_network