services:
# ========================== NGINX CONF ===============================
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx:inception
    env_file:
      - ./.env
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html:ro
    networks:
      - inception_network
    healthcheck:
      test: ["CMD-SHELL", "curl -k -f https://localhost:443 || exit 1"]
      interval: 30s 
      timeout: 10s
      retries: 3
      start_period: 20s
    depends_on:
      mariadb:
        condition: service_healthy
      wordpress:
        condition: service_healthy
# ========================== MARIADB CONF ===============================
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:inception
    container_name: mariadb
    env_file:
      - ./.env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network
    secrets:
      - db_password
      - db_root_password
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$(cat /run/secrets/db_root_password)"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: unless-stopped
# ========================== WORDPRESS CONF ===============================
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:inception
    env_file:
      - ./.env
    secrets:
      - db_password
      - wordpress_admin_password
      - proftpd_user_password
    restart: unless-stopped
    networks:
      - inception_network
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - wordpress_data:/var/www/html
    healthcheck:
      test: ["CMD-SHELL", "php-fpm7.4 -t"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
# ========================== REDIS CONF ===============================
  redis:
    container_name: redis
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    image: redis:inception
    env_file:
      - ./.env
    networks:
      - inception_network
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: unless-stopped
# ========================== FTP CONF ===============================
  proftpd:
    container_name: proftpd
    build:
      context: ./requirements/bonus/proftpd
      dockerfile: Dockerfile
    image: proftpd:inception
    env_file:
      - ./.env
    networks:
      - inception_network
    volumes:
      - wordpress_data:/var/www/html
    secrets:
      - proftpd_user_password
# ========================== VOLUMES ===============================
volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/lsilva-x/data/wordpress"
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/lsilva-x/data/mariadb"
# ========================== SECRETS ===============================
secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wordpress_admin_password:
    file: ../secrets/wordpress_admin_password.txt
  proftpd_user_password:
    file: ../secrets/proftpd_user_password.txt

# ========================== NETWORK ===============================
networks:
  inception_network:
    driver: bridge
    name: inception_network