version: "3"

services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx:inception
    env_file:
      - ./.env
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html:ro
    networks:
      - inception_network

# ========================== VOLUMES ===============================
volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/lsilva-x/data/wordpress"
